package kz.ata.saycheese.enums;

public enum State {
    MAIN,
    ORDERS,
    STORAGE,
    SELL,
    REPORTS,
    SUBORDERS,
    SUBREPORTS,
    SUBSTORAGE,
    SUBSELLS,
    ALL_ORDER,
    ACTIVE_ORDERS,
    ADD_ORDER,
    DELETE_ORDER,
    COMPLETE_ORDER,
    ALL_STORAGE,
    ADD_FOOD,
    DELETE_FOOD,
    ALL_TIME_REPORT,
    PERIOD_REPORT,
    SELL_PROCESSING,
    SELL_WEIGHT,

    ORDERS_DEFAULT
}
