package kz.ata.saycheese.enums;

public enum State {
    MAIN,
    ORDERS,
    STORAGE,
    COOK,
    COOK_PROCESSING,
    REPORTS,
    SUBREPORTS,
    ALL_ORDER,
    ACTIVE_ORDERS,
    ADD_ORDER,
    DELETE_ORDER,
    COMPLETE_ORDER,
    ALL_STORAGE,
    UPDATE_STORAGE,
    ALL_TIME_REPORT,
    PERIOD_REPORT,
    SELL_PROCESSING,
    SELL_WEIGHT,

    ORDERS_DEFAULT
}
